spring:
 profiles: 
  active: '@activeProfiles@'

---
spring: 
  profiles: dev
  devtools: 
    restart: 
      exclude: static/**
  datasource:
    url: jdbc:mariadb://144.168.59.111:3306/test?useUnicode=true&characterEncoding=utf-8
    username: test
    password: test1234
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: false
      pool-name: HikariCP
  jpa: 
    show-sql: true
    open-in-view: true
    properties:
      hibernate: 
        formate_sql: true
server: 
  port: 8090
logging: 
  config: classpath:config/logback.xml
  path: log
  level: 
    org: 
      hibernate:
        SQL: DEBUG
        type: 
          descriptor:
           sql:
            BasicBinder: TRACE