spring:
  datasource:
    url: jdbc:mysql://144.168.59.111:3306/test
    username: test
    password: test1234
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: com.mysql.jdbc.Driver