spring:
  datasource:
    url: jdbc:mariadb://144.168.59.111:3306/test
    username: test
    password: test1234
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: false
      pool-name: HikariCP